name: splinart
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - "docutils<0.21"
  - notebook
  - sphinx
  - nbsphinx
  - pydata-sphinx-theme
  - numpydoc
  - nbsphinx-link
  - myst-parser
